const SELECTED_MULTILIST_DEALS_ID = 77369
const DATE_TO_DEADLINE = Math.floor(Date.now() / 1000) + (3600 * 24)
const TASK_TYPE_ID = 2922842

module.exports = { SELECTED_MULTILIST_DEALS_ID, DATE_TO_DEADLINE, TASK_TYPE_ID }